name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 12 * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18.5

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Build
        id: build
        run: go run -v .

      - name: Generate sha256 hash
        if: steps.build.outputs.skip != 'true'
        run: |
          sha256sum geoip.db > geoip.db.sha256sum
          sha256sum geosite.db > geosite.db.sha256sum

      - name: Create a release
        run: |
          mkdir releases
          mv geoip.db releases/
          mv geosite.db releases/
          mv geoip.db.sha256sum releases/
          mv geosite.db.sha256sum releases/

      - name: Git push assets to "release" branch
        run: |
          cd releases || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "95022881+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release